name: 'Remove "safe to test" label'
description: 'Removes the "safe to test" label if the PR is a fork and the label is present'
inputs:
  label:
    description: 'The name of the lable that should be removed when it is present'
    required: false
    default: 'safe to test'
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'index.js'
