name: e2e-test

on:
  pull_request:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Replace @main with the commit hash of the latest commit on the pull request branch
      - uses: nilsreichardt/remove-safe-to-test-label@e243b60c985a16a711b80a211ee0539fef2d4ada
