name: e2e-test

on:
  pull_request_target:
    types: [labeled, synchronize, reopened]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      # Required to remove the "safe to build" label
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      # Replace @main with the commit hash of the latest commit on the pull request branch
      - uses: SharezoneApp/remove-safe-to-test-label@main
